package domain

type Weapon string

const (
	MOD_UNKNOWN        Weapon = "MOD_UNKNOWN"
	MOD_SHOTGUN        Weapon = "MOD_SHOTGUN"
	MOD_GAUNTLET       Weapon = "MOD_GAUNTLET"
	MOD_MACHINEGUN     Weapon = "MOD_MACHINEGUN"
	MOD_GRENADE        Weapon = "MOD_GRENADE"
	MOD_GRENADE_SPLASH Weapon = "MOD_GRENADE_SPLASH"
	MOD_ROCKET         Weapon = "MOD_ROCKET"
	MOD_ROCKET_SPLASH  Weapon = "MOD_ROCKET_SPLASH"
	MOD_PLASMA         Weapon = "MOD_PLASMA"
	MOD_PLASMA_SPLASH  Weapon = "MOD_PLASMA_SPLASH"
	MOD_RAILGUN        Weapon = "MOD_RAILGUN"
	MOD_LIGHTNING      Weapon = "MOD_LIGHTNING"
	MOD_BFG            Weapon = "MOD_BFG"
	MOD_BFG_SPLASH     Weapon = "MOD_BFG_SPLASH"
	MOD_WATER          Weapon = "MOD_WATER"
	MOD_SLIME          Weapon = "MOD_SLIME"
	MOD_LAVA           Weapon = "MOD_LAVA"
	MOD_CRUSH          Weapon = "MOD_CRUSH"
	MOD_TELEFRAG       Weapon = "MOD_TELEFRAG"
	MOD_FALLING        Weapon = "MOD_FALLING"
	MOD_SUICIDE        Weapon = "MOD_SUICIDE"
	MOD_TARGET_LASER   Weapon = "MOD_TARGET_LASER"
	MOD_TRIGGER_HURT   Weapon = "MOD_TRIGGER_HURT"
	MOD_NAIL           Weapon = "MOD_NAIL"
	MOD_CHAINGUN       Weapon = "MOD_CHAINGUN"
	MOD_PROXIMITY_MINE Weapon = "MOD_PROXIMITY_MINE"
	MOD_KAMIKAZE       Weapon = "MOD_KAMIKAZE"
	MOD_JUICED         Weapon = "MOD_JUICED"
	MOD_GRAPPLE        Weapon = "MOD_GRAPPLE"
)
